name: shadow-keeper

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to
permissions:
  # allow shadow-keeper collect data
  issues: read
  # allow deployment to GitHub Pages
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    name: Build job on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: shadow-keeper
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Prepare
        run: |
          mkdir -p ./site/public/api
      - name: Collect data
        run: |
          #
          # 在每个工作流程运行开始时，GitHub 会自动创建唯一的 GITHUB_TOKEN 机密以在工作流程中使用。 可以使用 GITHUB_TOKEN 在工作流程运行中进行身份验证。
          # [自动令牌身份验证](https://docs.github.com/zh/actions/security-guides/automatic-token-authentication)
          # [上下文](https://docs.github.com/en/actions/learn-github-actions/contexts)
          # echo $GITHUB_TOKEN // ${{ secrets.GITHUB_TOKEN }}
          #
          printf "{}" | tee ./site/public/api/mock.json
      - name: Run build site
        run: |
          pushd site
          npm install
          npm run build
          popd
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './site/dist'

  # Deployment job
  deploy:
    name: Deployment job on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
